### PR TITLE
Feat blog

### PR DESCRIPTION
**Pull request by csaument**
* Adds blog index page and components
* Adds blog post details page and components
* Connects blog data to backend
* Updates Chakra theme for blog components

### CODE REVIEW

**Comment by usama-maxenius** [comment]
Please fix the Conflicts

**Comment by csaument** [comment]
Conflicts resolved - they were with components that aren't used by the blog feature.

**Comment by usama-maxenius** [comment]
A couple of things that I would like to ask before I merge this 
- I have seen in some places you have used div instead of <Box>, was that used on purpose? Eventually Box also works in the same way by default but for the new components we are trying to as much components from chakra UI
- Just like the div you are also using Input field instead of which you can use https://chakra-ui.com/docs/components/input
- I have also seen you have created a separate interface for ISearchBody which I don't understand why was created for the blog feature because I haven't seen the blogs design yet 

Overall it looks good and we can still merge it if you want to cater the above changes later on

**Comment by csaument** [comment]
Fixed issue with appcontext - unknown origin/issue resolved by restoring file from origin/master.

**Review by usama-maxenius — APPROVED** [review]

**Review by usama-maxenius — APPROVED** [review]

**Pull request merged**
